- name: "Store LB DNS to local"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ANSIBLE_HOST_KEY_CHECKING: False
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"    
  roles:
    - kubernetes
    - awscli   
  tasks:
    - name: Configure access_key_id
      shell: "aws configure set aws_access_key_id {{ AWS_ACCESS_KEY_ID }}"
    - name: Configure secret_access_key
      shell: "aws configure set aws_secret_access_key {{ AWS_SECRET_ACCESS_KEY }}"
    - name: Configure default region
      shell: "aws configure set default.region {{ AWS_DEFAULT_REGION }}"
    - name: LB DNS
      # shell: "./bin/kubectl get services"
      # shell: "./bin/kubectl get svc --all-namespaces"
      shell: "./bin/kubectl get svc {{ ENVIRONMENT_NAME }}-service"
      register: elb_dns
      changed_when: false
      args:
        chdir: $HOME

    - name: Print to local file
      copy:
        content: "{{ elb_dns.stdout }}"
        dest: "~/elb_dns.txt"
      delegate_to: localhost