- name: "Store LB DNS locally"
  hosts: management[0]
  user: ec2-user
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  tasks:
    - name: Get LoadBalancer's DNS
      shell: "./bin/kubectl get svc {{ ENVIRONMENT_NAME }}-service"
      register: elb_dns
      args:
        chdir: $HOME

    - name: Print to local file
      copy:
        content: "{{ elb_dns.stdout }}"
        dest: "~/elb_dns.txt"
      delegate_to: localhost
  roles:
    - kubernetes